### ISSUE TITLE
Latest update says 13:44 22/03/2020

### ISSUE THREAD

**Issue by varun-deepblueai** [covid-19-au/covid-19-au.github.io#106]
The latest stateCaseData.json update gives the "updatedTime" as "13:44 22/03/2020".

I suspect this is incorrect, as the previous update gave the update time as "08:57 26/03/2020"

**Comment by varun-deepblueai** [comment]
This has now been updated to "updatedTime": "21:53 25/03/2020"

Is this correct? It looks like it was updated on the 26th, not 25th.

**Comment by covid-19-au** [comment]
Thanks for the reminding. Now it should be fixed.

**Comment by covid-19-au** [comment]
The issue is fixed
