### ISSUE TITLE
[feature request] Implement optional population normalisation and log axes

### ISSUE THREAD

**Issue by sgay** [covid-19-au/covid-19-au.github.io#112]
Hi there,

Would it be possible to have an option for all state data to be per 100,000 population, and also plot the charts in log view? Perhaps radio buttons up the top. I would offer to do this myself but have 0 experience with JS.

Thanks very much for the fantastic resource.

**Comment by gamma032steam** [comment]
Thanks for the suggestion and we're glad you found the site helpful.

We'll be adding a toggle to the map so you can view cases and tests per 1 million people.

A log scale is being considered carefully as the data changes. We don't plan on adding it to the backlog just yet.
