### ISSUE TITLE
Text overflowed on iPhone X Safari

### ISSUE THREAD

**Issue by wahyd4** [covid-19-au/covid-19-au.github.io#136]
Some of the texts for the table headers are overflowed on mobile devices.  Please see the image below for details.

![IMG_9823](https://user-images.githubusercontent.com/836576/77984935-c1935600-735e-11ea-950d-65bb924ec854.PNG)

Besides, looks like the `State` has a larger font size than others.

https://github.com/covid-19-au/covid-19-au.github.io/blob/71538c0855138792cc67067e10efe1d58d1cabc6/src/App.css#L140-L144

**Comment by freddiewanah** [comment]
Hi wahyd4, can you provide your iPhone model as well?

**Comment by freddiewanah** [comment]
Thanks, will fix this in next deploy
