### ISSUE TITLE
Australian - State Colours 

### ISSUE THREAD

**Issue by blisx264** [covid-19-au/covid-19-au.github.io#146]
/* Code segment for COVID Site State Colour  array - StateGraph.js - Line 5

// Based on CanvasJS theme 1. Avoids two purple series and preserves colours day-to-day.
const colourMapping = {
 
 "NSW": "#99CCFF",
  "VIC": "#000099",
  "QLD": "#660033",
  "WA":  "#000000",
  "SA":  "#CC0000",
  "TAS": "#009900",
  "ACT": "#FFCC00",
  "NT":  "#FF6600"
}

![image](https://user-images.githubusercontent.com/62640119/78106871-b102de80-7437-11ea-8200-103f36801dbd.png)

**Comment by freddiewanah** [comment]
Right, can u contact to me through Email? freddie.wanah@gmail.com

**Comment by blisx264** [comment]
> Right, can u contact to me through Email? [freddie.wanah@gmail.com](mailto:freddie.wanah@gmail.com)

Ive tried twice, might want to check spam ?
