### ISSUE TITLE
Difference between confirmed and existing cases

### ISSUE THREAD

**Issue by boxedpaul** [covid-19-au/covid-19-au.github.io#16]
In the historical data charts, it’s not clear what the difference is between confirmed and cases.

Can you add definitions to the charts, please?

**Comment by ghostryder77** [comment]
In may 1997 there was a case about a boy that seemed to have just a common cold but it was a influenza virus. That came from the birds the CDC is running test on 7 cases that was founded as A(H5N1) there was a subtype B also but couldn't get the reagents of it . 2 of those was deaths. the boy wasn't on a respiratory machine to keep him alive . The other patient was older and caught pneumonia and  killed him.  If this is A and B mutation into a C type virus we are in trouble.  It would have been from May 19th till December 30th 1997 with 7 cases and to confirmed deaths .

**Comment by freddiewanah** [comment]
Hey Paul, to clarify, are you asking the difference between the confirmed cases in the first chart and the new cases in the second one?

**Comment by boxedpaul** [comment]
Hi Freddie,

On the "Trends for COVID-19 Cases in Australia" chart, I interpreted the Existing line as meaning the existing cases from the day before, and Confirmed as the latest number of confirmed cases.

If that is true, I would expect Existing to be identical to Confirmed, but trailing by a day. It seems it's something else, but it's not clear what it is.

My question is: what is the definition of "Confirmed" and "Existing" cases?

**Comment by gamma032steam** [comment]
'Existing' was the total number of confirmed cases, less recoveries and deaths.

We heard that the label was unintuitive, so the series has been removed in #95.

Thanks for the feedback!
