### ISSUE TITLE
[Feature Request] Source of Transmission for Cases

### ISSUE THREAD

**Issue by renlord** [covid-19-au/covid-19-au.github.io#174]
Knowing if a case is a foreign-acquired vs local transmission is quite important to track epidemology with the new quarantine rules instated.

**Comment by gamma032steam** [comment]
Would be a helpful and valuable feature. I can work on this if we have the data. 

Looks like [NSW is reporting](https://www.health.nsw.gov.au/news/Pages/20200407_00.aspx) and there's a [daily updated graph](https://www.health.gov.au/resources/publications/covid-19-cases-in-australia-by-state-and-source-of-transmission). @wooyunlong?

Also, be nice on the assignment testing please :)

**Comment by freddiewanah** [comment]
@BoxHezi Is working on this
