### ISSUE TITLE
Add time since on new posts

### ISSUE THREAD

**Issue by notoriousturtle** [covid-19-au/covid-19-au.github.io#35]
For each entry under "News Timeline", include a 'post x minutes/hours ago'.

**Comment by freddiewanah** [comment]
I think currently the published time is right upon the title(for mobile view) and to the left of title(on large screens). Adding a posted x minutes ago might be redundant

**Comment by notoriousturtle** [comment]
Oh, so it is. When you shrink it down to a smaller size it doesn't wrap. It just cuts it off. CSS bug?

**Comment by freddiewanah** [comment]
Yeah, it's a bug.

**Comment by PenguinPP** [comment]
Hello @notoriousturtle , could you tell me what screen size you are using?

**Comment by blisx264** [comment]
The scrolling div is too large for the MOBILE viewport. It's there if you scroll down.

**Comment by notoriousturtle** [comment]
Working now.
