### ISSUE TITLE
Number of recoveries - VIC

### ISSUE THREAD

**Issue by blaw36** [covid-19-au/covid-19-au.github.io#37]
Hi - thanks to your team, this is fantastic. Any chance you can update the number of recoveries from Victoria through the DHHS media releases? As of the last day or two, they now disclose number of recovered cases daily, eg:
https://www.dhhs.vic.gov.au/more-covid-19-cases-confirmed-victoria-21-march-2020

Unfortunately at about that time the Aus gov website (presumably where your headline figure was coming from) has stopped disclosing too which makes things a little more difficult :(

**Comment by freddiewanah** [comment]
Hey, our team is working hard to keep all the status data up to date. We did face issues about the gov disclose some related data sources. If you can find some accountable data sources on recovered cases, inform us please, we'll do a quick update once confirmed.

**Comment by blaw36** [comment]
So Victorian gov has released from 3 days ago, and hopefully will continue to track:
(Date, cumul. recovered)
(19/3: 28)
(20/3: 39)
(21/3: 51)

https://www.dhhs.vic.gov.au/more-covid-19-cases-confirmed-victoria-19-march-2020
https://www.dhhs.vic.gov.au/more-covid-19-cases-confirmed-victoria-20-march-2020
https://www.dhhs.vic.gov.au/more-covid-19-cases-confirmed-victoria-21-march-2020

**Comment by covid-19-au** [comment]
Thank you for reminding. We have updated our site according to that resource.

**Comment by blaw36** [comment]
Thanks. I wish the other states would also publish recovery data, it's just as important. Your team is doing a great job - keep it up!
