### ISSUE TITLE
Data for Victoria 12 October is incorrect by about 1 order of magnitude

### ISSUE THREAD

**Issue by kortschak** [covid-19-au/covid-19-au.github.io#641]
The Victorian Government data shows 19,229 recovered cases for Victoria.

![Screenshot from 2020-10-12 16-02-19](https://user-images.githubusercontent.com/275221/95708712-7c07fc00-0ca4-11eb-8f7e-469cb359f025.png)

while the covid-19-au site shows 192,229, resulting in a newly recovered count of 173,011 for that day.

![Screenshot from 2020-10-12 16-02-45](https://user-images.githubusercontent.com/275221/95708822-c8ebd280-0ca4-11eb-9bc3-cbb0695c07e4.png)

**Comment by freddiewanah** [comment]
thanks for reminding us of this issue, we are fixing it now
