### ISSUE TITLE
 Ranking criterion

### ISSUE THREAD

**Issue by unswit** [covid-19-au/covid-19-au.github.io#65]
Wow! Great Job! It's really helpful to alert people about the situation.

I also have a suggestion here:

Insert the number of newly confirmed as a ranking criterion. During this time( Rapid growth period), the most important information is the newly confirmed every day.

**Comment by freddiewanah** [comment]
@unswit deployed your suggestion, happy to reopen if more features a needed

**Comment by unswit** [comment]
Thanks! Really nice work!
