### ISSUE TITLE
Add state by state trendlines

### ISSUE THREAD

**Issue by joshcarp** [covid-19-au/covid-19-au.github.io#9]
Love the website

I think it'd be cool to have a section that had all the trend-lines for each state

**Comment by freddiewanah** [comment]
Hey Josh, thanks for the suggestion, we're working on this feature and will let you know when released.

**Comment by mailkondal** [comment]
I would love this feature to be added soon too.

**Comment by gamma032steam** [comment]
This will be on the site soon. Thanks for the suggestion!
