### ISSUE TITLE
Cases by State map not shading NSW (possibly since cases > 999)

### ISSUE THREAD

**Issue by BJReplay** [covid-19-au/covid-19-au.github.io#99]
The Cases by State appears to be reading (current as at 21:37 AEDT 25-Mar) 1,029 NSW cases as 1 NSW case (not handling the comma thousands separator).
![image](https://user-images.githubusercontent.com/37993507/77527810-f75cb880-6ee0-11ea-92f8-c2a4d488094d.png)

**Comment by gamma032steam** [comment]
Thanks for pointing that out.

I think we fixed this it the latest release. Could you check it again to confirm?

**Comment by BJReplay** [comment]
Looking good!
